### ISSUE TITLE
`Reline::Terminfo::TerminfoError` error

### ISSUE THREAD

**Issue by ogirginc** [DarthSim/overmind#132]
Has anyone encountered an error like this before?

```
web    | [2581] ! Unable to load application: Reline::Terminfo::TerminfoError: The terminfo database could not be found.
web    | bundler: failed to load command: puma (/Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/puma)
worker | 2022-06-07T12:46:19.563Z pid=2700 tid=bj8 WARN: Reline::Terminfo::TerminfoError: The terminfo database could not be found.
```

I can run the commands from `Procfile` manually. However, `overmind start` fails. 

<details>
<summary>Here is the full logs</summary>

```
web                | [2581] ! Unable to load application: Reline::Terminfo::TerminfoError: The terminfo database could not be found.
web                | bundler: failed to load command: puma (/Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/puma)
worker             | 2022-06-07T12:46:19.563Z pid=2700 tid=bj8 WARN: Reline::Terminfo::TerminfoError: The terminfo database could not be found.
web                | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/terminfo.rb:108:in `setupterm': The terminfo database could not be found. (Reline::Terminfo::TerminfoError)
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:21:in `<class:ANSI>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:6:in `<main>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
worker             | 2022-06-07T12:46:19.563Z pid=2700 tid=bj8 WARN: /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/terminfo.rb:108:in `setupterm'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:21:in `<class:ANSI>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:6:in `<main>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:580:in `<main>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:580:in `<main>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
web                | 	from /Users/ogirginc/teamtailor/config/application.rb:9:in `<top (required)>'
web                | 	from /Users/ogirginc/teamtailor/config/environment.rb:3:in `require_relative'
web                | 	from /Users/ogirginc/teamtailor/config/environment.rb:3:in `<top (required)>'
web                | 	from config.ru:4:in `require_relative'
web                | 	from config.ru:4:in `block in <main>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
worker             | /Users/ogirginc/teamtailor/config/application.rb:9:in `<top (required)>'
worker             | /Users/ogirginc/teamtailor/config/environment.rb:3:in `require_relative'
worker             | /Users/ogirginc/teamtailor/config/environment.rb:3:in `<top (required)>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/cluster.rb:357:in `run'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/puma:25:in `load'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/puma:25:in `<top (required)>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:273:in `boot_application'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:37:in `run'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/bin/sidekiq:31:in `<top (required)>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/sidekiq:25:in `load'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/sidekiq:25:in `<top (required)>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
web                | 	from /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
worker             | /Users/ogirginc/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
worker             | Exited
web                | Exited
```

</details>

I am clueless at this stage and will take any help I can. 😅 Thank you!

**Comment by dzemlianoi-double** [comment]
The same stuff started happening today.

If i run all the commands separately in different terminals (web, api, worker) - everything seems to work ok.

**Comment by ogirginc** [comment]
I can also confirm commenting out those lines does solve the problem. Created an issue on https://github.com/ruby/reline/issues/447 too.

**Comment by jsteen-mpr** [comment]
For me, this turned out to be an issue with Homebrew's tmux version 3.3. Overmind uses tmux to run the `Procfile` processes. As a test, I removed Overmind from the picture by running `tmux` directly, and running the process (rails) inside it still crashed with the same terminfo error.

As a workaround, I added the line `set -g default-terminal screen-256color` in my `~/.config/tmux/tmux.conf`. This was based on one of the suggested fixes here:  
https://github.com/Homebrew/homebrew-core/issues/102748#issuecomment-1145378599  
This was my preferred fix because it didn't involve changing Homebrew or system files. Others may choose something that works better for their environment, or wait to see if this is resolved in a post-3.3 tmux release in Homebrew.

I'm using macOS Catalina 10.15.7.

**Comment by simonhutchings** [comment]
`brew uninstall --ignore-dependencies tmux`

then 

`brew install tmux`

worked for me

**Comment by thomasklemm** [comment]
Can confirm that @simonhutchings workaround worked for me too.

**Comment by nicalpi** [comment]
Ok, in case anyone finds this, for me none of the recommendations worked.


I've just upgraded to Mac OS Ventura on an M1 and at the same time upgraded a lot of homebrew packages.

So while I was having the same symptoms, I don't know what was at fault.

But, while I was having this issue with Reline, I also had a new issue in Tmux where my backspace stopped working. Tmux 3.3a.

While researching that issue I found this https://stackoverflow.com/questions/23848061/cannot-get-delete-key-to-work-with-tmux-and-osx

And the code in the answer actually both fixed my Reline issue with Overwind as well as my issue with the backspace.

```
brew install ncurses
$(brew --prefix)/opt/ncurses/bin/infocmp tmux-256color > ~/tmux-256color.info
tic -xe tmux-256color ~/tmux-256color.info

#https://github.com/tmux/tmux/issues/1257#issuecomment-581378716
#https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
```

Hope it can help someone that, like me, decided to upgrade its system on a Friday off :D

**Comment by michaelglass** [comment]
I got here because I updated nixpkgs to 22.11 which pulls in a newer tmux.

The source of the problem is not overmind or reline but tmux changing its default term color and MacOs not supporting the tmux settings by default.

Many of the comments will help, but @nicalpi's comment is the one [suggested by tmux author.](https://github.com/tmux/tmux/issues/3218#issue-1265998468)

(newish ncurses from nix also works to solve the problem, you don't need to use it from brew).

**Comment by venelrene** [comment]
Glad I was able to find this thread

Till this day,  @simonhutchings workaround worked for me too.
